= README

Device: M5PaperS3

== Installation

=== Install Required Software and Flash Firmware

. Flash the latest UIFlow2 firmware using link:https://burner.m5stack.com/firmwares?device=2093000000000000018&keyword=papers3&firmware=1897200000000000284[the website] or the link:https://docs.m5stack.com/en/uiflow/m5burner/intro[M5 burner] application.
+
Set "Boot Option" to "Run main.py directly".

NOTE: Press and hold the power button until the LED on the back of the device flashes green to enter flashing mode.

. Install link:https://docs.micropython.org/en/latest/reference/mpremote.html[mpremote] for communicating with the firmware

Once the firmware is installed, the device can be powered on by pressing the power button once, and powered off by pressing it twice.

=== (Optional) Update the Words List

The words which the device will cycle through are held in link:./word_list.txt[word_list.txt]. Update this list to add or remove words.

Whenever this list is updated, you will need to run the `build_json.py` script and copy the newly generated json file over to the device.

== Create environment.json file

Create the file `device_files/environment.json` with the following template:

[source]
----
{
    "TIME_ZONE": "GMT+1",
    "WORD_REFRESH_PERIOD_SECONDS": 1800,
    "WIFI": {
        "YOUR_SSID": "YOUR_PASSWORD"
    }
}
----

If these are not provided, the following defaults will apply:

[cols="1,1"]
|===
|Key |Default Value

|`TIME_ZONE`
|`GMT+0`

|`WORD_REFRESH_PERIOD_SECONDS`
|`1800`

|`WIFI`
|`{}` (no SSIDs)
|===

NOTE: WiFi is only enabled once at device startup and used for NTP synchronisation. If no predefined networks are available, sync will be skipped.

== Flash to Device

. Run `build_json.py` to build the `words.json` file containing the required word information.

. Copy the data files over:
+
[,shell]
----
mpremote fs cp ./device_files/words.json :/flash/words.json
mpremote fs cp ./device_files/environment.json :/flash/environment.json
mpremote fs cp ./device_files/environment.json :/flash/environment.json
----

. Copy the script files over:
+
[,shell]
----
mpremote fs cp ./boot.py :/flash/boot.py
mpremote fs cp ./main.py :/flash/main.py
----

NOTE: When the device is not connected to the computer, a single press of the power button will power it on. A double press will turn it off. The screen does not clear on power-off, you can tell if it is actually powered off by seeing if it responds to touch events.

== Run as Debug

. Write the latest data files to the device:
+
[,shell]
----
mpremote fs cp ./device_files/words.json :/flash/words.json
mpremote fs cp ./device_files/environment.json :/flash/environment.json
mpremote fs cp ./device_files/environment.json :/flash/environment.json
----

. Run the script as debug:
+
    mpremote connect /dev/ttyACM0 run ./main.py


== Credits

* phonetics.csv: https://github.com/kaysting/english-dictionary/releases
* meanings.csv: https://github.com/kaysting/english-dictionary/releases
* dictionary.csv: https://raw.githubusercontent.com/CloudBytes-Academy/English-Dictionary-Open-Source/refs/heads/main/csv/dictionary.csv
* Usage examples primarily taken from https://www.worddb.com/sentences and https://dictionary.cambridge.org/dictionary/english